### ISSUE TITLE
how do i start it?

### ISSUE THREAD

**Issue by oskarsci** [wowthecoder/dank-memer-button-update-autotyper#1]

**Comment by Bosspenguinsus** [comment]
yes how

**Comment by Bosspenguinsus** [comment]
actually this script looks really cool but don't know how to start

**Comment by Cookie4Free** [comment]
So for me this worked:
1. go to the bot folder
2. type into the directory "cmd" to open cmd with the path of the folder
3. type in "python discord_auto_typer[updated].py" (you can type "disc" and press tab 2x for autofill)
4. if modules are missing you have to install them. windows will tell you which are missing.
5. repeat 3. until it works

This modules I had to install:
python -m pip install --upgrade pip --user
pip install win10toast
pip install win10toast-click

**Comment by wowthecoder** [comment]
Run the program like how @Cookie4Free suggested, then if you are running the program for the first time, follow the instructions in the Readme file and fill in the required info. 
In the future, whenever you start the program, it will ask you whether to configure bot or not. Just press the enter/return key to start the program normally.

**Comment by wowthecoder** [comment]
By the way I have updated the Readme file to include clearer instructions
