### ISSUE TITLE
i can only open the repeat commands file

### ISSUE THREAD

**Issue by Bosspenguinsus** [wowthecoder/dank-memer-button-update-autotyper#3]
i can't open the other files

**Comment by wowthecoder** [comment]
You probably need to install the missing modules. Try to right click on the py file (discord_autotyper or gamble_for_levels), then select the option "Edit with IDLE". After you open the IDLE, run the file from there. It will show you which error it is and which modules you are missing. Then you can go to cmd and use the pip tool to install the modules.

**Comment by wowthecoder** [comment]
Let me know when you have resolved the problem so I can close this issue.

**Comment by Bosspenguinsus** [comment]
thnx a lot this script is really useful I solved my problem
